apiVersion: v1
kind: Service
metadata:
  name: new-website
#  labels:
#    name: new-website
spec: 
  ports:
    - port: 80 
      targetPort: 5000        
      protocol: TCP
  selector:
    app: new-website
  type: LoadBalancer
