apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: new-website
spec:
  replicas: 4
  selector:
    matchLabels:
      app: new-website
  template: 
    metadata:
      labels:
        app: new-website
    spec:   
      containers: 
      - name: new-website
        image: gcr.io/fast-gke/new-website:1.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
