apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: new-website-certificate
spec:
  domains:
    - v2.beta.fast.co
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: new-website
spec:
  replicas: 4
  selector:
    matchLabels:
      app: new-website
  template:
    metadata:
      labels:
        app: new-website
    spec:
      containers:
        - name: new-website
          image: gcr.io/fast-gke/new-website
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: new-website-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: new-website-ip-address
    networking.gke.io/managed-certificates: new-website-certificate
spec:
  backend:
    serviceName: new-website
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: new-website
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: new-website
